### Inscription de test8
POST http://127.0.0.1:8000/user/register/
Content-Type: application/json

{
  "username": "test8",
  "password": "ComplexPassword123!",
  "email": "test8@test.fr",
  "birth_date": "2000-01-01",
  "can_be_contacted": true,
  "can_data_be_shared": false
}

### Inscription de test9
POST http://127.0.0.1:8000/user/register/
Content-Type: application/json

{
  "username": "test9",
  "password": "ComplexPassword123!",
  "email": "test9@test.fr",
  "birth_date": "2000-01-01",
  "can_be_contacted": true,
  "can_data_be_shared": false
}

### Authentification de test8
POST http://127.0.0.1:8000/user/token/
Content-Type: application/json

{
  "username": "test8",
  "password": "ComplexPassword123!"
}

### Authentification de test9
POST http://127.0.0.1:8000/user/token/
Content-Type: application/json

{
  "username": "test9",
  "password": "ComplexPassword123!"
}

### ===================================== PROJECT =====================================

### test8 crée un projet
POST http://127.0.0.1:8000/project/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODEyMTYzLCJpYXQiOjE3MTk3MjU3NjMsImp0aSI6IjUzNTM4ZDZhMDA3ZDQwNGJhOWE5MDk2OWQ3YjQzNjlkIiwidXNlcl9pZCI6MX0.bCRoaPAj0Nk2Bp4viL9-3LqKdyzphetfpgjoPM7MAv8
Content-Type: application/json

{
  "name": "Project by test8",
  "description": "Description of project by test8",
  "type_project": "FRONT_END"
}

### test8 ajoute test9 comme contributeur
PUT http://127.0.0.1:8000/project/contributors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODEyMTYzLCJpYXQiOjE3MTk3MjU3NjMsImp0aSI6IjUzNTM4ZDZhMDA3ZDQwNGJhOWE5MDk2OWQ3YjQzNjlkIiwidXNlcl9pZCI6MX0.bCRoaPAj0Nk2Bp4viL9-3LqKdyzphetfpgjoPM7MAv8
Content-Type: application/json

{
  "user": 2,
  "project": 1
}

### ===================================== ISSUES ======================================

### test9 crée une issue dans le projet de test8
POST http://127.0.0.1:8000/project/issue/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODEyMTczLCJpYXQiOjE3MTk3MjU3NzMsImp0aSI6IjE0YmUxMjhkMDdmNDQ5MjdiNzc0MjU0NjkxNmEyZjI3IiwidXNlcl9pZCI6Mn0.Sm5W2NzjKXTlkOVAXLliDzsXMuU5q_ezCbI0cHfzX4A
Content-Type: application/json

{
  "title": "Issue by test9",
  "description": "Description of issue by test9",
  "priority": "HIGH",
  "tag": "FEATURE",
  "status": "TODO",
  "project": 1,
  "assignee": 2
}

### test8 crée un commentaire sur l'issue de test9
POST http://127.0.0.1:8000/project/comment/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODEyMTYzLCJpYXQiOjE3MTk3MjU3NjMsImp0aSI6IjUzNTM4ZDZhMDA3ZDQwNGJhOWE5MDk2OWQ3YjQzNjlkIiwidXNlcl9pZCI6MX0.bCRoaPAj0Nk2Bp4viL9-3LqKdyzphetfpgjoPM7MAv8
Content-Type: application/json

{
  "issue": 1,
  "body" : "Comment by test8 on issue by test9"
}

### test9 met à jour l'issue
PATCH http://127.0.0.1:8000/project/issue/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODEyMTczLCJpYXQiOjE3MTk3MjU3NzMsImp0aSI6IjE0YmUxMjhkMDdmNDQ5MjdiNzc0MjU0NjkxNmEyZjI3IiwidXNlcl9pZCI6Mn0.Sm5W2NzjKXTlkOVAXLliDzsXMuU5q_ezCbI0cHfzX4A
Content-Type: application/json

{
  "title": "Updated Issue by test9"
}

### test8 supprime le commentaire sur l'issue de test9
DELETE http://127.0.0.1:8000/project/comment/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5ODEyMTYzLCJpYXQiOjE3MTk3MjU3NjMsImp0aSI6IjUzNTM4ZDZhMDA3ZDQwNGJhOWE5MDk2OWQ3YjQzNjlkIiwidXNlcl9pZCI6MX0.bCRoaPAj0Nk2Bp4viL9-3LqKdyzphetfpgjoPM7MAv8
