### ====================================== USERS ====================================== OK!
### Afficher tout les users
GET http://127.0.0.1:8000/user/all/?page=2
### Inscription d'un utilisateur
POST http://127.0.0.1:8000/user/register/
Content-Type: application/json

{
  "username": "test5",
  "password": "ComplexPassword123!",
  "email": "tata@tata.fr",
  "birth_date": "2000-01-01",
  "can_be_contacted": true,
  "can_data_be_shared": false
}
### Authentification d'un utilisateur pour obtenir le token JWT
POST http://127.0.0.1:8000/user/token/
Content-Type: application/json

{
  "username": "test8",
  "password": "ComplexPassword123!"
}
### Rafraîchissement du token JWT (remplacer <refresh_token> par le token réel)
POST http://127.0.0.1:8000/user/token-refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMDE1Njc5NywiaWF0IjoxNzE5NTUxOTk3LCJqdGkiOiI2MTU3OTllYjdiNGE0NzIzYWNlNjcwMTA4MTViOThkZCIsInVzZXJfaWQiOjF9.y2-s2K8EtckPauW7SlmkcCqiQDCckkkufUYTbqmfnO0"
}
### Récupérer les détails de l'utilisateur (remplacer <access_token> par le token réel)
GET http://127.0.0.1:8000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgwMTYwLCJpYXQiOjE3MTk2OTM3NjAsImp0aSI6IjY5MGRmZDU0ZWU4MjRjNTdiNTc3NGMzYjNlOWRmOGYxIiwidXNlcl9pZCI6MX0.yY4v2YK33pcZrQVW3nIWouq-hkLvSkmAfkmsEbVYZs0
### Mettre à jour les détails de l'utilisateur (remplacer <access_token> par le token réel)
PUT http://127.0.0.1:8000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NjM4NDUyLCJpYXQiOjE3MTk1NTE5OTcsImp0aSI6ImUyNTE4ZTg3YTMxMDQ1ODI5ZjhkYTA4ZjA3MTRhYTVmIiwidXNlcl9pZCI6MX0.U4e6aj3WBi1841OxGVaQSvjREJg2oisvt5nS85xHZLw
Content-Type: application/json

{
  "username": "test",
  "password": "ComplexPassword123!",
  "email": "tata@tata.fr",
  "birth_date": "2000-01-01",
  "can_be_contacted": true,
  "can_data_be_shared": true
}
### Supprimer l'utilisateur (remplacer <access_token> par le token réel)
DELETE http://127.0.0.1:8000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NjM4NDUyLCJpYXQiOjE3MTk1NTE5OTcsImp0aSI6ImUyNTE4ZTg3YTMxMDQ1ODI5ZjhkYTA4ZjA3MTRhYTVmIiwidXNlcl9pZCI6MX0.U4e6aj3WBi1841OxGVaQSvjREJg2oisvt5nS85xHZLw
### ===================================================================================












### ===================================== PROJECT =====================================
### Créer un projet (remplacer <access_token> par le token réel)
POST http://127.0.0.1:8000/project/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgwOTE3LCJpYXQiOjE3MTk2OTQ1MTcsImp0aSI6ImNjNjJhNDAyZThjMDRmYjk5YzBjNjFkYzg5NjE1YTUyIiwidXNlcl9pZCI6MX0.4I6yCUU3bPTVwsg20h4Mx5Gji-ftJp9yd68cKjJ7mcM
Content-Type: application/json

{
  "name": "test1",
  "description": "Project",
  "type_project": "FRONT_END"
}
### ============================== OK!
### Récupérer la liste des projets (remplacer <access_token> par le token réel)
GET http://127.0.0.1:8000/project/all/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTIzOTk3LCJpYXQiOjE3MTk4Mzc1OTcsImp0aSI6IjViY2I4YmY5YmMxMzRmMDY4ODdmYTBiNWNmNWYxYWIyIiwidXNlcl9pZCI6MX0.n_xFi9c7oWcMZX_hXEoUEmcG6UkUBdJzLwOeUtWvjHA
### ============================== OK!
### Récupérer les détails d'un projet (remplacer <access_token> par le token réel et <project_id> par l'ID du projet)
GET http://127.0.0.1:8000/project/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgxNDYxLCJpYXQiOjE3MTk2OTUwNjEsImp0aSI6IjUyZWEzMzJiMjhiYzRlNTZiN2RlOTQ4MzkzNGFjMjZkIiwidXNlcl9pZCI6MX0.9dYW18GzbjV3TqccTXkKgkniqaMnpcMggZN4Rg3mUSk
### ============================== OK!
### Mettre à jour un projet (remplacer <access_token> par le token réel et <project_id> par l'ID du projet)
PUT http://127.0.0.1:8000/project/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgwMTAxLCJpYXQiOjE3MTk2OTM3MDEsImp0aSI6ImJjNmY5ZTRlMGU4YTQ5ZjRhNTg3OTYzN2UzZGU0ODBkIiwidXNlcl9pZCI6Mn0.PxMoT3G7g-CCFgtyVjLIp94ysmUGXeYHQ0Cxe6p-B64
Content-Type: application/json

{
  "name": "Uupdaaaaaaaaaaaaaad Project Name",
  "description": "Updated Project Description",
  "type_project": "FRONT_END"
}
### ============================== OK!
### Mettre à jour un projet (remplacer <access_token> par le token réel et <project_id> par l'ID du projet)
PATCH http://127.0.0.1:8000/project/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgwNzc4LCJpYXQiOjE3MTk2OTQzNzgsImp0aSI6ImU0ZGExOGYyYmU2NzRjZGNhZDMxYTU2NTMxODQ2NmQwIiwidXNlcl9pZCI6MX0.eiMGPCcinsV37mPTIPCK5vzSGvpYCPLmhJHZcYl1K0Y
Content-Type: application/json

{
  "name": "Prct Name"
}
### ============================== OK!
### Supprimer un projet (remplacer <access_token> par le token réel et <project_id> par l'ID du projet)
DELETE http://127.0.0.1:8000/project/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzY5MjAxLCJpYXQiOjE3MTk2ODI4MDEsImp0aSI6IjQ1YzU3ZjFhMGQ3NzRhOTU4Yjg0YjBlZGVkNGIwMDliIiwidXNlcl9pZCI6M30.f23hzF0XECxL3daki21sl6Q-pDB_WqMyqVEh8YCwZV4
### ============================== OK!
### Ajouter un contributeur à un projet (remplacer <access_token> par le token réel et <project_id> par l'ID du projet)
PUT http://127.0.0.1:8000/project/contributors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgwOTE3LCJpYXQiOjE3MTk2OTQ1MTcsImp0aSI6ImNjNjJhNDAyZThjMDRmYjk5YzBjNjFkYzg5NjE1YTUyIiwidXNlcl9pZCI6MX0.4I6yCUU3bPTVwsg20h4Mx5Gji-ftJp9yd68cKjJ7mcM
Content-Type: application/json

{
  "user": 2,
  "project": 1
}
### ============================== OK! 
DELETE http://127.0.0.1:8000/project/contributors/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgwODM4LCJpYXQiOjE3MTk2OTQ0MzgsImp0aSI6ImM5OTI4Y2I1MWZlZTQ5YmM4MTRlMzc2NGVjYTY5NzQ4IiwidXNlcl9pZCI6Mn0.d-hrVogmY-_wbl8E3PHB0EgBJPHWX6Pb7Ob13rYXxKw
Content-Type: application/json

{
  "user": 2,
  "project": 1
}
### ============================== OK!
### ===================================================================================












### ===================================== ISSUES ======================================
### Créer une issue (remplacer <access_token> par le token réel)
POST http://127.0.0.1:8000/project/issue/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NzgzMjczLCJpYXQiOjE3MTk2OTY4NzMsImp0aSI6Ijk0MjUzN2FlZWMxYTQzZDliYTg5OWRhMGMyMzEwOTI0IiwidXNlcl9pZCI6Mn0.vyvFSFO-fizACnTGYjmMWsdlhk_5xqMkl1b_7gdf4V4
Content-Type: application/json

{
  "title": "test",
  "description": "Issue Description",
  "priority": "HIGH",
  "tag": "FEATURE",
  "status": "TODO",
  "project": 1,
  "assignee": 2
}
### ============================== OK!
### Récupérer la liste des issues (remplacer <access_token> par le token réel)
GET http://127.0.0.1:8000/project/issue/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTI0MTE2LCJpYXQiOjE3MTk4Mzc3MTYsImp0aSI6Ijk3Yjg1NTM1YWM1ZjQ0NjM4NGIyNzdkMDA2NWFjMTY4IiwidXNlcl9pZCI6MX0.yJ89j1y7cWrhZnqfu4isFlShDjj1S4nze7_0Ap1mY1Q

### ============================== OK!
### Récupérer les détails d'une issue (remplacer <access_token> par le token réel et <issue_id> par l'ID de l'issue)
GET http://127.0.0.1:8000/project/issue/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTI0MTE2LCJpYXQiOjE3MTk4Mzc3MTYsImp0aSI6Ijk3Yjg1NTM1YWM1ZjQ0NjM4NGIyNzdkMDA2NWFjMTY4IiwidXNlcl9pZCI6MX0.yJ89j1y7cWrhZnqfu4isFlShDjj1S4nze7_0Ap1mY1Q

### ============================== OK!
PUT http://127.0.0.1:8000/project/issue/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5Nzg3NDcyLCJpYXQiOjE3MTk3MDEwNzIsImp0aSI6IjUzMmNhZjU0MDJmMjQyY2JhNWQ1M2ExZTY5ZDkyNGEzIiwidXNlcl9pZCI6Mn0.xNO9nGI-pNWpr2jxyKkkn0GxVgkWd-zUQhUhIe04sjU
Content-Type: application/json

{
  "title": "Updated Issue Title",
  "description": "Updated Issue Description",
  "priority": "MEDIUM",
  "tag": "BUG",
  "status": "IN_PROGRESS",
  "project": 1
}
### Mettre à jour une issue (remplacer <access_token> par le token réel et <issue_id> par l'ID de l'issue)
PATCH http://127.0.0.1:8000/project/issue/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5Nzg3NDcyLCJpYXQiOjE3MTk3MDEwNzIsImp0aSI6IjUzMmNhZjU0MDJmMjQyY2JhNWQ1M2ExZTY5ZDkyNGEzIiwidXNlcl9pZCI6Mn0.xNO9nGI-pNWpr2jxyKkkn0GxVgkWd-zUQhUhIe04sjU
Content-Type: application/json

{
  "title": "Titles"
}
### DETELE ISSUE
DELETE http://127.0.0.1:8000/project/issue/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5Nzg3NDcyLCJpYXQiOjE3MTk3MDEwNzIsImp0aSI6IjUzMmNhZjU0MDJmMjQyY2JhNWQ1M2ExZTY5ZDkyNGEzIiwidXNlcl9pZCI6Mn0.xNO9nGI-pNWpr2jxyKkkn0GxVgkWd-zUQhUhIe04sjU
### ============================== OK!
### ===================================================================================












### ===================================== COMMENT ======================================
### Créer une comment (remplacer <access_token> par le token réel)
POST http://127.0.0.1:8000/project/comment/create/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTI0MTE2LCJpYXQiOjE3MTk4Mzc3MTYsImp0aSI6Ijk3Yjg1NTM1YWM1ZjQ0NjM4NGIyNzdkMDA2NWFjMTY4IiwidXNlcl9pZCI6MX0.yJ89j1y7cWrhZnqfu4isFlShDjj1S4nze7_0Ap1mY1Q
Content-Type: application/json

{
  "issue": 1,
  "body" : "test"
}
### Récupérer la liste des comments (remplacer <access_token> par le token réel)
GET http://127.0.0.1:8000/project/comment/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTI0MTE2LCJpYXQiOjE3MTk4Mzc3MTYsImp0aSI6Ijk3Yjg1NTM1YWM1ZjQ0NjM4NGIyNzdkMDA2NWFjMTY4IiwidXNlcl9pZCI6MX0.yJ89j1y7cWrhZnqfu4isFlShDjj1S4nze7_0Ap1mY1Q

### ============================== OK!
### Récupérer les détails d'une comment (remplacer <access_token> par le token réel et <issue_id> par l'ID de l'issue)
GET http://127.0.0.1:8000/project/comment/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTI0MTE2LCJpYXQiOjE3MTk4Mzc3MTYsImp0aSI6Ijk3Yjg1NTM1YWM1ZjQ0NjM4NGIyNzdkMDA2NWFjMTY4IiwidXNlcl9pZCI6MX0.yJ89j1y7cWrhZnqfu4isFlShDjj1S4nze7_0Ap1mY1Q
### ============================== OK!
### Mettre à jour une comment (remplacer <access_token> par le token réel et <issue_id> par l'ID de l'issue)
PATCH http://127.0.0.1:8000/project/comment/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5Nzg3NDgzLCJpYXQiOjE3MTk3MDEwODMsImp0aSI6ImE1NjkxMmU3ZjY5YzQ5MGY5YzZkMTViYjJjYTc1YTAzIiwidXNlcl9pZCI6MX0.N_JnSDHR5QuGRgZxtWa5yowcJV4l4PLn2EuN27iPp70
Content-Type: application/json

{
  "body" : "Hello World!"
}
### ============================== OK!
### DELETE Comment
DELETE http://127.0.0.1:8000/project/comment/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5Nzg3NDgzLCJpYXQiOjE3MTk3MDEwODMsImp0aSI6ImE1NjkxMmU3ZjY5YzQ5MGY5YzZkMTViYjJjYTc1YTAzIiwidXNlcl9pZCI6MX0.N_JnSDHR5QuGRgZxtWa5yowcJV4l4PLn2EuN27iPp70















